title: "Rubyで創るRPG"
summary: |-
  十四歳のお誕生日のお祝いにとMacBook Air を贈られた 未來(みらい)。
  憧れの遙香(はるか)お姉様から、プログラミングを教えてもらえることに。

  コンピュータの仕組みを学ぶところから始まり、RPG(ロールプレイングゲーム)を創り上げていきます。

  毎週一回の掲載予定です。お楽しみに。

topics: ["Ruby", "初心者", "コンピュータ", "計算機科学", "プログラミング"]
published: true
published_at: 2023-11-23 06:00
price: 2000
toc_depth: 2
chapters:
  - 01-life
  - 02-etymology
  - 03-history
